package com.view;

/**
 *
 * @author Lisbelis
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setTitle("Sistema de Red de Computadoras - Simulador de Enrutamiento");
        // --- ACTIVANDO LOS PLACEHOLDERS ELEGANTES DE FLATLAF ---
        txtIdNodo.putClientProperty("JTextField.placeholderText", "Ej: 1");
        txtNombreNodo.putClientProperty("JTextField.placeholderText", "Ej: PC-Gerencia");
        txtTipoDato.putClientProperty("JTextField.placeholderText", "Ej: 192.168.1.1 o 4");
        txtOrigenId.putClientProperty("JTextField.placeholderText", "Ej: 1");
        txtDestinoId.putClientProperty("JTextField.placeholderText", "Ej: 2");
        txtPeso.putClientProperty("JTextField.placeholderText", "Ej: 15");
        tablaResultados.setModel(new javax.swing.table.DefaultTableModel(
                null, new String[]{"Esperando cálculo... (Presione Calcular)"}
        ));

        // ESTO FUERZA EL ANCHO:
        javax.swing.table.TableColumn colInicial = tablaResultados.getColumnModel().getColumn(0);
        colInicial.setPreferredWidth(380);
        colInicial.setMinWidth(350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlContenedorConfig = new javax.swing.JPanel();
        pnlRegistroNodos = new javax.swing.JPanel();
        lblIdNodo = new javax.swing.JLabel();
        txtIdNodo = new javax.swing.JTextField();
        lblNombreNodo = new javax.swing.JLabel();
        txtNombreNodo = new javax.swing.JTextField();
        lblTipoDato = new javax.swing.JLabel();
        txtTipoDato = new javax.swing.JTextField();
        lblTipoNodo = new javax.swing.JLabel();
        cbTipoNodo = new javax.swing.JComboBox();
        btnAgregarNodo = new javax.swing.JButton();
        pnlConexionesRed = new javax.swing.JPanel();
        lblOrigenId = new javax.swing.JLabel();
        lblDestinoId = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        txtOrigenId = new javax.swing.JTextField();
        txtDestinoId = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        btnAgregarConexion = new javax.swing.JButton();
        pnlEstadoTopologia = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JTextArea();
        pnlMapaRed = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnLimpiarPanel = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaResultados = new javax.swing.JTable();
        btnCalcular = new javax.swing.JButton();
        btnResetear = new javax.swing.JButton();
        btnGuardarSesion = new javax.swing.JButton();
        btnLimpiarTodo = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 245, 245));

        pnlContenedorConfig.setBackground(new java.awt.Color(200, 202, 201));

        pnlRegistroNodos.setBorder(javax.swing.BorderFactory.createTitledBorder("REGISTRO DE DISPOSITIVOS"));
        pnlRegistroNodos.setForeground(new java.awt.Color(0, 0, 0));
        pnlRegistroNodos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        lblIdNodo.setText("ID:");

        lblNombreNodo.setText("Nombre:");

        lblTipoDato.setText("Dato(IP/Puertos):");

        lblTipoNodo.setText("Tipo:");

        cbTipoNodo.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Router", "Computadora"}));

        btnAgregarNodo.setBackground(new java.awt.Color(0, 112, 184));
        btnAgregarNodo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAgregarNodo.setForeground(new java.awt.Color(255, 255, 235));
        btnAgregarNodo.setText("Agregar Nodo");

        javax.swing.GroupLayout pnlRegistroNodosLayout = new javax.swing.GroupLayout(pnlRegistroNodos);
        pnlRegistroNodos.setLayout(pnlRegistroNodosLayout);
        pnlRegistroNodosLayout.setHorizontalGroup(
                pnlRegistroNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlRegistroNodosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlRegistroNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombreNodo)
                                        .addComponent(txtTipoDato)
                                        .addGroup(pnlRegistroNodosLayout.createSequentialGroup()
                                                .addGroup(pnlRegistroNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblIdNodo)
                                                        .addComponent(txtIdNodo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(pnlRegistroNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(pnlRegistroNodosLayout.createSequentialGroup()
                                                                .addComponent(lblTipoNodo)
                                                                .addGap(127, 127, 127))
                                                        .addComponent(cbTipoNodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(pnlRegistroNodosLayout.createSequentialGroup()
                                                .addGroup(pnlRegistroNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblTipoDato)
                                                        .addComponent(lblNombreNodo))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(btnAgregarNodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        pnlRegistroNodosLayout.setVerticalGroup(
                pnlRegistroNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlRegistroNodosLayout.createSequentialGroup()
                                .addContainerGap(24, Short.MAX_VALUE)
                                .addGroup(pnlRegistroNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblIdNodo)
                                        .addComponent(lblTipoNodo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlRegistroNodosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtIdNodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbTipoNodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblNombreNodo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombreNodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(lblTipoDato)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTipoDato, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarNodo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
        );

        pnlConexionesRed.setBorder(javax.swing.BorderFactory.createTitledBorder("CONFIGURACIÓN DE ENLACES"));

        lblOrigenId.setText("ID Origen:");

        lblDestinoId.setText("ID Destino:");

        lblPeso.setText("Latencia(ms):");

        txtOrigenId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrigenIdActionPerformed(evt);
            }
        });

        txtDestinoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinoIdActionPerformed(evt);
            }
        });

        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });

        btnAgregarConexion.setBackground(new java.awt.Color(0, 112, 184));
        btnAgregarConexion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAgregarConexion.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarConexion.setText("Conectar");

        javax.swing.GroupLayout pnlConexionesRedLayout = new javax.swing.GroupLayout(pnlConexionesRed);
        pnlConexionesRed.setLayout(pnlConexionesRedLayout);
        pnlConexionesRedLayout.setHorizontalGroup(
                pnlConexionesRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlConexionesRedLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlConexionesRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPeso)
                                        .addGroup(pnlConexionesRedLayout.createSequentialGroup()
                                                .addGroup(pnlConexionesRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblOrigenId)
                                                        .addComponent(txtOrigenId, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                                .addGroup(pnlConexionesRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtDestinoId, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblDestinoId)))
                                        .addGroup(pnlConexionesRedLayout.createSequentialGroup()
                                                .addComponent(lblPeso)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(btnAgregarConexion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        pnlConexionesRedLayout.setVerticalGroup(
                pnlConexionesRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlConexionesRedLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlConexionesRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblOrigenId)
                                        .addComponent(lblDestinoId))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlConexionesRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtOrigenId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDestinoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblPeso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarConexion, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                .addGap(21, 21, 21))
        );

        pnlEstadoTopologia.setBorder(javax.swing.BorderFactory.createTitledBorder("DISPOSITIVOS Y ENLACES ACTIVOS"));

        txtConsola.setColumns(20);
        txtConsola.setRows(5);
        jScrollPane1.setViewportView(txtConsola);

        pnlMapaRed.setMinimumSize(new java.awt.Dimension(600, 400));
        pnlMapaRed.setPreferredSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout pnlMapaRedLayout = new javax.swing.GroupLayout(pnlMapaRed);
        pnlMapaRed.setLayout(pnlMapaRedLayout);
        pnlMapaRedLayout.setHorizontalGroup(
                pnlMapaRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlMapaRedLayout.setVerticalGroup(
                pnlMapaRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlEstadoTopologiaLayout = new javax.swing.GroupLayout(pnlEstadoTopologia);
        pnlEstadoTopologia.setLayout(pnlEstadoTopologiaLayout);
        pnlEstadoTopologiaLayout.setHorizontalGroup(
                pnlEstadoTopologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEstadoTopologiaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlEstadoTopologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(pnlMapaRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                                .addContainerGap())
        );
        pnlEstadoTopologiaLayout.setVerticalGroup(
                pnlEstadoTopologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEstadoTopologiaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnlMapaRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        btnEliminar.setBackground(new java.awt.Color(0, 112, 184));
        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar Nodo");

        btnLimpiarPanel.setBackground(new java.awt.Color(0, 112, 184));
        btnLimpiarPanel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLimpiarPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarPanel.setText("Limpiar Panel");
        btnLimpiarPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContenedorConfigLayout = new javax.swing.GroupLayout(pnlContenedorConfig);
        pnlContenedorConfig.setLayout(pnlContenedorConfigLayout);
        pnlContenedorConfigLayout.setHorizontalGroup(
                pnlContenedorConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlContenedorConfigLayout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addGroup(pnlContenedorConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pnlRegistroNodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnlConexionesRed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(98, 98, 98)
                                .addGroup(pnlContenedorConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pnlEstadoTopologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnlContenedorConfigLayout.createSequentialGroup()
                                                .addComponent(btnLimpiarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(511, Short.MAX_VALUE))
        );
        pnlContenedorConfigLayout.setVerticalGroup(
                pnlContenedorConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlContenedorConfigLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(pnlContenedorConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(pnlContenedorConfigLayout.createSequentialGroup()
                                                .addComponent(pnlRegistroNodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(pnlConexionesRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlContenedorConfigLayout.createSequentialGroup()
                                                .addComponent(pnlEstadoTopologia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(pnlContenedorConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnLimpiarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(142, Short.MAX_VALUE))
        );

        pnlConexionesRed.getAccessibleContext().setAccessibleName("CONFIGURACION DE ENLACES");

        jTabbedPane1.addTab("Topología", pnlContenedorConfig);

        jPanel4.setBackground(new java.awt.Color(200, 202, 201));

        tablaResultados.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane2.setViewportView(tablaResultados);

        btnCalcular.setBackground(new java.awt.Color(0, 112, 184));
        btnCalcular.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Ejecutar Floyd-Warshall");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnResetear.setBackground(new java.awt.Color(0, 112, 184));
        btnResetear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnResetear.setForeground(new java.awt.Color(255, 255, 255));
        btnResetear.setText("Reseteo");
        btnResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetearActionPerformed(evt);
            }
        });

        btnGuardarSesion.setBackground(new java.awt.Color(0, 112, 184));
        btnGuardarSesion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGuardarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarSesion.setText("Guardar Resultados");

        btnLimpiarTodo.setBackground(new java.awt.Color(0, 112, 184));
        btnLimpiarTodo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLimpiarTodo.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarTodo.setText("Limpiar Tabla");
        btnLimpiarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(448, 448, 448)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(btnCalcular)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnGuardarSesion)
                                                .addGap(12, 12, 12)
                                                .addComponent(btnLimpiarTodo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnResetear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(603, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(78, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnGuardarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnLimpiarTodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnResetear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(55, 55, 55))
        );

        jTabbedPane1.addTab("Matriz de Caminos Cortos", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOrigenIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrigenIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrigenIdActionPerformed

    private void txtDestinoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinoIdActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarPanelActionPerformed

    private void btnResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetearActionPerformed

    private void btnLimpiarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarConexion;
    private javax.swing.JButton btnAgregarNodo;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarSesion;
    private javax.swing.JButton btnLimpiarPanel;
    private javax.swing.JButton btnLimpiarTodo;
    private javax.swing.JButton btnResetear;
    private javax.swing.JComboBox cbTipoNodo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDestinoId;
    private javax.swing.JLabel lblIdNodo;
    private javax.swing.JLabel lblNombreNodo;
    private javax.swing.JLabel lblOrigenId;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblTipoDato;
    private javax.swing.JLabel lblTipoNodo;
    private javax.swing.JPanel pnlConexionesRed;
    private javax.swing.JPanel pnlContenedorConfig;
    private javax.swing.JPanel pnlEstadoTopologia;
    private javax.swing.JPanel pnlMapaRed;
    private javax.swing.JPanel pnlRegistroNodos;
    private javax.swing.JTable tablaResultados;
    private javax.swing.JTextArea txtConsola;
    private javax.swing.JTextField txtDestinoId;
    private javax.swing.JTextField txtIdNodo;
    private javax.swing.JTextField txtNombreNodo;
    private javax.swing.JTextField txtOrigenId;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtTipoDato;
    // End of variables declaration//GEN-END:variables

    public void mostrarMatrizResultados(int[][] matriz, java.util.List<com.model.Nodo> listaNodos) {
        int n = listaNodos.size();
        String[] columnas = new String[n + 1];
        columnas[0] = "Origen \\ Destino";
        for (int i = 0; i < n; i++) {
            com.model.Nodo nodo = listaNodos.get(i);
            columnas[i + 1] = "ID: " + nodo.getIdNodo() + " (" + nodo.getNombre() + ")";
        }
        Object[][] datos = new Object[n][n + 1];
        for (int i = 0; i < n; i++) {
            com.model.Nodo nodoFila = listaNodos.get(i);
            datos[i][0] = "ID: " + nodoFila.getIdNodo() + " (" + nodoFila.getNombre() + ")";
            for (int j = 0; j < n; j++) {
                int valor = matriz[i][j];
                datos[i][j + 1] = (valor >= 999999) ? "∞" : valor;
            }
        }
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(datos, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaResultados.setModel(modelo);
        tablaResultados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        javax.swing.table.DefaultTableCellRenderer renderizadorCentrado = new javax.swing.table.DefaultTableCellRenderer();
        renderizadorCentrado.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        for (int i = 0; i < tablaResultados.getColumnCount(); i++) {
            javax.swing.table.TableColumn columna = tablaResultados.getColumnModel().getColumn(i);
            javax.swing.table.TableCellRenderer headerRenderer = tablaResultados.getTableHeader().getDefaultRenderer();
            java.awt.Component comp = headerRenderer.getTableCellRendererComponent(tablaResultados, columna.getHeaderValue(), false, false, 0, i);
            int anchoDeseado = comp.getPreferredSize().width + 40;
            columna.setPreferredWidth(anchoDeseado);
            columna.setMinWidth(anchoDeseado);
            if (i > 0) columna.setCellRenderer(renderizadorCentrado);
        }
    }

    private void formatearTabla() {
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        for (int i = 0; i < tablaResultados.getColumnCount(); i++) tablaResultados.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        tablaResultados.setRowHeight(35);
        tablaResultados.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        tablaResultados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); // Permite scroll horizontal si hay muchos nodos
        tablaResultados.getColumnModel().getColumn(0).setPreferredWidth(180);
    }

    public javax.swing.JTextField getTxtIdNodo() {
        return txtIdNodo;
    }

    public javax.swing.JTextField getTxtNombreNodo() {
        return txtNombreNodo;
    }

    public javax.swing.JComboBox<String> getCbTipoNodo() {
        return cbTipoNodo;
    }

    public javax.swing.JTextField getTxtTipoDato() {
        return txtTipoDato;
    }

    public javax.swing.JButton getBtnAgregarNodo() {
        return btnAgregarNodo;
    }

    public javax.swing.JTextField getTxtOrigenId() {
        return txtOrigenId;
    }

    public javax.swing.JTextField getTxtDestinoId() {
        return txtDestinoId;
    }

    public javax.swing.JTextField getTxtPeso() {
        return txtPeso;
    }

    public javax.swing.JButton getBtnAgregarConexion() {
        return btnAgregarConexion;
    }

    public javax.swing.JTextArea getTxtConsola() {
        return txtConsola;
    }

    public javax.swing.JTable getTablaResultados() {
        return tablaResultados;
    }

    public javax.swing.JButton getBtnCalcular() {
        return btnCalcular;
    }

    public javax.swing.JButton getBtnEliminar() {
        return btnEliminar;
    }

    public javax.swing.JPanel getPnlMapaRed() {
        return pnlMapaRed;
    }

    public javax.swing.JButton getBtnResetear() {
        return btnResetear;
    }

    public javax.swing.JButton getBtnLimpiarPanel() {
        return btnLimpiarPanel;
    }

    public javax.swing.JButton getBtnGuardarSesion() {
        return btnGuardarSesion;
    }

    public javax.swing.JButton getBtnLimpiarTodo() {
        return btnLimpiarTodo;
    }
}